---
functional:
  - A user must be able to play a simple battle without signing up
  - A user must be able to sign in with email and password
  - A user must be able to sign in with a Github account
  - A user must be able to sign in with a Discord account
  - A user must be able to sign up with nickname, email and password
  - A user must be able to sign up with a Github account
  - A user must be able to sign up with a Discord account
  - A user must be able to change their password
  - A user must be able to sign out
  - A user must be able to play with any other user, a bot or a friend
  - A user must be able to choose a game by difficulty level
  - A user must be able to choose a specific or random game
  - A user must be able to change a programming language in a game
  - Tasks in games are available in 2 languages - English and Russian
  - Players must be able to see each other's code editors and test outputs
  - Users as guests must be able to watch players' games in real time
  - Completed games are available as replays. The code editor is displayed like a playback interface.
  - Users earn points, which are used to create weekly, monthly, and all-time rankings
  - A registered user must be able to chat on the website
  - A user must be able to change their username
non-functional:
  - The website must be designed with usability in mind and optimized for performance
  - The website must be secure and protect user data
  - The website must be user-friendly on mobile devices
  - The website must be compatible with the latest browser versions
  - The website must be capable of handling high traffic (e.g., 1,000 simultaneous users)
implicit:
  - All interface elements must be rendered correctly
  - All external links must be opened in a new browser tab
  - Since the project is open source, it must have a link to its repository
  - The website should preserve login sessions when closed and reopened, allowing users to remain signed in without having to re-authenticate
